version: "3"

tasks:
  build:
    cmds:
      - templ generate
      - go run . --act=build

  dev:templ:
    cmds:
      - templ generate -watch --proxy="http://localhost:8080" --cmd="go run . --act=web"

  dev:web:
    cmds:
      - task: build
      - go run . --act=web
  
  test:
    cmds:
      - go test ./...

  dev:watch:
    cmds:
      # pip install watchdog[watchmedo]
      - > 
        ~/venv/bin/watchmedo auto-restart 
        --patterns "*.templ;*.go;*.css;*.js" 
        -i "*_templ.go"
        -i "build/*"
        --recursive
        -- sh -c "task dev:web; sleep infinity"
