version: "3"

tasks:
  build:
    cmds:
      - templ generate
      - go run . build

  dev:templ:
    cmds:
      - templ generate -watch --proxy="http://localhost:8080" --cmd="go run . web"

  dev:web:
    cmds:
      - templ generate
      - go run . web
  
  test:
    cmds:
      - go test ./...

  dev:watch:
    cmds:
      # pip install watchdog[watchmedo]
      - > 
        ~/venv/bin/watchmedo auto-restart 
        --patterns "*.templ;*.go;*.css;*.js;*.md" 
        -i "*_templ.go;build/*"
        -d blog
        --recursive
        -- sh -c "task dev:web; sleep infinity"
