version: "3"

tasks:
  build:
    cmds:
      - templ generate
      - go run . --act=build

  dev:templ:
    cmds:
      - templ generate -watch --proxy="http://localhost:8080" --cmd="go run . --act=web"

  dev:web:
    cmds:
      - task: build
      - go run . --act=web
  
  test:
    cmds:
      - go test ./...
