{
 "title": "My App by Logs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Max Over Time By Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time({service_name=\"app-logs\"} | json | duration > 0 | url_path!=\"\" | unwrap duration [2m]) by (url_pattern)"
    }
   ]
  },
  {
   "title": "Count of Requests By Pattern",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"app-logs\"} | json | duration > 0 | url_path!=\"\" [2m])) by (url_pattern)"
    }
   ]
  },
  {
   "title": "P50 Duration By Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.50,{service_name=\"app-logs\"} | json | duration > 0 | unwrap duration [10m]) by (url_pattern)"
    }
   ]
  },
  {
   "title": "Count of Requests By Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"app-logs\"} | json | duration > 0 | url_path!=\"\" [2m])) by (url_pattern)"
    }
   ]
  },
  {
   "title": "Avg Duration By Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({service_name=\"app-logs\"} | json | duration > 0 | unwrap duration [10m]) by (url_pattern)"
    }
   ]
  }
 ]
}