name: CI

on:
  push:
    branches: ["master"]

jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: darklab8/infra/.github/actions/install-go@master
      
      - name: Install Taskfile
        uses: darklab8/infra/.github/actions/install-taskfile@master

      - name: Install Templ
        uses: darklab8/infra/.github/actions/install-templ@master    

      - name: build
        run: task build
        env:
            SITE_ROOT: "/blog/"

      - uses: actions/upload-pages-artifact@v1
        with:
            name: github-pages
            path: ./build

      - name: Deploy to pages
        uses: actions/deploy-pages@v1
        id: deployment
