name: CI

on:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    # every month
    - cron: '30 10 * * 0'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: darklab8/infra/.github/actions/install-go@master

      - name: Install Taskfile
        uses: darklab8/infra/.github/actions/install-taskfile@master

      - name: Install Templ
        uses: darklab8/infra/.github/actions/install-templ@master   

      - name: build
        run: task build
        env:
            SITE_ROOT: "/blog/"

      - name: Test
        run: task test
