name: CI

on:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    # every month
    - cron: '30 10 * * 0'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.21

      - name: Install Task
        run: |
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.2.513

      - name: build
        run: task build
        env:
            SITE_ROOT: "/darklab_blog/"

      - name: Test
        run: task test
